In [1]:
import joblib
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
model_lr = joblib.load('./dataset/wikipedia_classification')

/home/lutfianto/anaconda3/envs/tensorflow/lib/python3.8/site-packages/sklearn/base.py:318: UserWarning: Trying to unpickle estimator LogisticRegression from version 1.0.2 when using version 1.2.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(


In [3]:
new_data = np.asarray([2, 5, 336, 0, 0, 0, 0, 0])

In [4]:
new_data.reshape(1,-1)

array([[  2,   5, 336,   0,   0,   0,   0,   0]])

In [5]:
model_lr.predict([new_data])

/home/lutfianto/anaconda3/envs/tensorflow/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0])

In [6]:
data_dict = {2:[2, 5, 336, 0, 0, 0, 0, 0]}

In [7]:
new_dict = list(data_dict.values())

In [10]:
data_dict.values()

dict_values([[2, 5, 336, 0, 0, 0, 0, 0]])

In [11]:
new_dict

[[2, 5, 336, 0, 0, 0, 0, 0]]

In [8]:
new_data.reshape(1, -1)

array([[  2,   5, 336,   0,   0,   0,   0,   0]])

In [9]:
if model_lr.predict(new_dict) == 0:
    print('Popluler')
else:
    print('Unpopuler')

Popluler


/home/lutfianto/anaconda3/envs/tensorflow/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
